### ISSUE TITLE
Visual Bug | Plants in a pond makes water invisible 

### ISSUE THREAD

**Issue by L0WSP0T** [juraj-hrivnak/Greenery#19] opened 2023-11-16 16:46 UTC
Here are pictures that show what I mean!

Before

![image](https://github.com/juraj-hrivnak/Greenery/assets/128107978/58f36116-bf7d-41bf-9ef0-e355bbb3eab8)

After

![image](https://github.com/juraj-hrivnak/Greenery/assets/128107978/901f3c77-b226-46e4-83aa-0f7724a65914)

**Comment by juraj-hrivnak** [comment] 2023-11-16 16:49
Please send me your latest.log.
What version of Fluidlogged API do you use?
Do you have any other mods installed?

**Comment by Nykrdaudr** [comment] 2023-11-18 15:47
Hi, it was me that actually found the bug. just reported it to Lowspot, since im playing on his (sligthly modified) modpack.
here is the stuff you want:
Fluidlogged = v2.2.4
other mods? a lot. 
![image](https://github.com/juraj-hrivnak/Greenery/assets/64286618/5a5f43e0-a1c2-4fd1-a859-c5fd9ef5452c)

[latest.log](https://github.com/juraj-hrivnak/Greenery/files/13400747/latest.log)

**Comment by juraj-hrivnak** [comment] 2023-11-18 15:50
Can you try it with the latest version of Fluidlogged API from Modrinth?

**Comment by Nykrdaudr** [comment] 2023-11-18 16:01
how to re-create (with my current mods and default settings on Fluidlogged v2.2.7)
1. make a 2x2 hole in the ground
2. fill with water
3. place 4 plants inside it.
the water sometimes returns to normal after breaking one or more plants (seems random how many i have to break)

[latest.log](https://github.com/juraj-hrivnak/Greenery/files/13400779/latest.log)

**Comment by Nykrdaudr** [comment] 2023-11-18 16:23
tried once more, with extensive logging turned on, from fluidlogged
(from debug.log)
![image](https://github.com/juraj-hrivnak/Greenery/assets/64286618/909328d5-2605-4119-9cab-8d6c009e0796)

**Comment by Nykrdaudr** [comment] 2023-11-18 22:52
hi again. im sorry for wasting your time.
i got the same bug with a glass pane, just now.
turns out it was optifine all along. (render regions)

**Comment by juraj-hrivnak** [comment] 2023-11-19 15:05
Okay, no problem. I’m closing this.

**Closed by juraj-hrivnak** 2023-11-19 15:05 UTC
Labels: bug, missing info

**Comment by erialsan** [comment] 2024-11-15 15:16
I reproduced this issue without Optifine. I think it is probably Vintagium, but I will open another issue when I can investigate further.
