### ISSUE TITLE
Crash on creating new world

### ISSUE THREAD

**Issue by Lach01298** [juraj-hrivnak/Greenery#10] opened 2023-03-11 02:57 UTC
[crash-2023-03-11_13.55.40-server.txt](https://github.com/juraj-hrivnak/Greenery/files/10947436/crash-2023-03-11_13.55.40-server.txt)

**Comment by juraj-hrivnak** [comment] 2023-03-11 06:48
I need to update the Fiuidlogged API.
Until then you can use v1.9.0.6

**Comment by juraj-hrivnak** [comment] 2023-03-11 12:53
Fixed in `v3.1`

**Comment by Lach01298** [comment] 2023-03-12 03:31
Still happens in 3.1 with latest Fluidlogged API.
[crash-2023-03-12_14.29.53-server.txt](https://github.com/juraj-hrivnak/Greenery/files/10949916/crash-2023-03-12_14.29.53-server.txt)

**Comment by juraj-hrivnak** [comment] 2023-03-12 07:40
Interesting. Try to delete the config file for Greenery. It looks like there is error in parsing it.

**Comment by Lach01298** [comment] 2023-03-12 23:25
Deleted configs, still get the same crash.

**Comment by juraj-hrivnak** [comment] 2023-03-12 23:29
Can you send the full latest.log?

**Comment by juraj-hrivnak** [comment] 2023-03-13 17:28
@Lach01298
I still can not reproduce this.
Can you send the full latest log and, if possible, the debug log too, and also the config file?

**Comment by juraj-hrivnak** [comment] 2023-03-13 20:41
Oh okay, now I know what’s causing it. Biome configured in the config doesn’t exist.

**Comment by FranklinMCA** [comment] 2023-03-13 20:42
Hey! I have the same problem here.
[crash-2023-03-13_21.41.30-server.txt](https://github.com/juraj-hrivnak/Greenery/files/10961748/crash-2023-03-13_21.41.30-server.txt)

**Comment by juraj-hrivnak** [comment] 2023-03-13 20:44
For now you can fix the issue by removing the biomesoplenty:pasture biome from the barley’s world gen config.

**Comment by FranklinMCA** [comment] 2023-03-14 00:06
It works. Thank u for your help!

**Closed** 2023-03-19 14:41 UTC
Labels: bug
